### ISSUE TITLE
[v417] SmartContract execution => Credits Node error: Transaction in progress

### ISSUE THREAD

**Issue by micmac0** [CREDITSCOM/node#28]
**Describe the bug**
I tried to reproduce issue #27 with parameter to force smartcontract execution in config.ini.
Chain was resolving around 10 blocks / 20 sec as initial conditions.
The first 6 exections were ok but after I got 4 error like this : 
```
com.credits.client.node.exception.NodeClientException: Credits Node error: Transaction in progress
	at com.credits.client.node.util.NodeClientUtils.processApiResponse(NodeClientUtils.java:31)
	at com.credits.client.node.service.NodeApiServiceImpl.callTransactionFlow(NodeApiServiceImpl.java:211)
	at com.credits.client.node.service.NodeApiServiceImpl.smartContractTransactionFlow(NodeApiServiceImpl.java:179)
	at org.credits.load.loadtest.DoSendSmartContractThread.doSend(DoSendSmartContractThread.java:161)
	at org.credits.load.loadtest.DoSendSmartContractThread.run(DoSendSmartContractThread.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

please find logs in attached files 
[log_TxInProgress.tar.gz](https://github.com/CREDITSCOM/node/files/3298393/log_TxInProgress.tar.gz)

**Comment by DmitriyYashenko** [comment]
On 13 successful calls in the executive (upper half), I see 13 successful saves in the blockchain (lower half). Part of the transaction was delayed (max. 26 seconds), the delay m. many different reasons, including the lag of the node itself. No transaction was lost please find logs in attached files
<img src="https://i.paste.pics/da0a5152e93d1b00031830f67d54a5d7.png" align="center">
